name: Build and Deploy Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 重要！确保后续推送权限正确

      # 步骤 2: 预处理 Markdown（单 $ → $$）
      - name: Preprocess Markdown files
        run: |
          find . -name "*.md" -exec sed -i -E 's/([^\\]|^)\$([^$]|$)/\1$$\2/g' {} \;

      # 步骤 3: Jekyll 构建
      - name: Build with Jekyll
        uses: jerryjvl/jekyll-action@v1
        with:
          enable_safe: true  # 保持与 GitHub Pages 的安全模式兼容
          target_branch: gh-pages  # 指定部署分支

      # 步骤 4: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成，无需手动配置
          publish_dir: ./_site  # Jekyll 默认输出目录
          keep_files: false     # 清理旧文件
          force_orphan: true    # 强制使用单次提交历史

      # 步骤 5: 更新构建状态徽章（可选）
      - name: Update Status Badge
        run: |
          # 生成状态徽章链接（需手动添加到 README.md）
          echo "构建状态徽章 Markdown 代码:"
          echo "[![Jekyll Site Status](https://github.com/${{ github.repository }}/workflows/Build%20and%20Deploy%20Site/badge.svg)](https://github.com/${{ github.repository }}/actions)"
